USE [master]
GO

/****** Object:  Database [Bajaj]    Script Date: 06/07/2016 08:06:35 ******/
CREATE DATABASE [Bajaj] ON  PRIMARY 
( NAME = N'Bajaj', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\Bajaj.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Bajaj_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\Bajaj_log.LDF' , SIZE = 504KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Bajaj] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Bajaj].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Bajaj] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Bajaj] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Bajaj] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Bajaj] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Bajaj] SET ARITHABORT OFF 
GO

ALTER DATABASE [Bajaj] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Bajaj] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Bajaj] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Bajaj] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Bajaj] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Bajaj] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Bajaj] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Bajaj] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Bajaj] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Bajaj] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Bajaj] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Bajaj] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Bajaj] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Bajaj] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Bajaj] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Bajaj] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Bajaj] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Bajaj] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Bajaj] SET  READ_WRITE 
GO

ALTER DATABASE [Bajaj] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Bajaj] SET  MULTI_USER 
GO

ALTER DATABASE [Bajaj] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Bajaj] SET DB_CHAINING OFF 
GO

