//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BajajProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BykeImage
    {
        public int ID { get; set; }
        public Nullable<int> BykeID { get; set; }
        public string ImageType { get; set; }
        public string ImageURL { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Byke Byke { get; set; }
    }
}
