//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BajajProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceCompany
    {
        public FinanceCompany()
        {
            this.Finance_Insuarance = new HashSet<Finance_Insuarance>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> MinimumDownPaymentAmmount { get; set; }
        public Nullable<int> Interest { get; set; }
        public Nullable<int> AdditionalCharges { get; set; }
        public Nullable<int> InsuaranceCompanyID { get; set; }
        public Nullable<int> MaxLoanAmmount { get; set; }
        public Nullable<int> MaxDuration { get; set; }
        public string LogoURL { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Finance_Insuarance> Finance_Insuarance { get; set; }
        public virtual InsuaranceCompany InsuaranceCompany { get; set; }
    }
}
