//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BajajProj.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BajajDBContext : DbContext
    {
        public BajajDBContext()
            : base("name=BajajDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Byke> Bykes { get; set; }
        public DbSet<BykeImage> BykeImages { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Finance_Insuarance> Finance_Insuarance { get; set; }
        public DbSet<FinanceCompany> FinanceCompanies { get; set; }
        public DbSet<InsuaranceCompany> InsuaranceCompanies { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
